[package]
name = "kernel-x86_64"
version = "0.1.0"
edition = "2021"

[dependencies]
kernel = { path = "../kernel" }
aml = "0.16.0"
acpi = "4.1.0"
uefi = "0.12.0"
x86_64 = "0.14.6"
uart_16550 = "0.2.0"
modular-bitfield = "0.11.2"
buddy_system_allocator = "0.8.0"